version: '3.0'
services:
  rasa-demo-actions:
    image: rasa/rasa-demo-actions:latest
    security_opt:
      - seccomp:unconfined
    build:
      context: .
      dockerfile: Dockerfile.actions
    ports:
      - 5055:5055
    user: "$UID:$GID"

  rasa-demo:
    image: rasa/rasa:2.8.3-full
    security_opt:
      - seccomp:unconfined
    ports:
      - 5005:5005
    user: "$UID:$GID"
    volumes:
      - ./:/app
    command:
      - run